exec: q2_input.o baggage.o luggage_security.o weight.o boarding_pass.o immigration.o passport.o visa.o main.c #security.o male_security.o main.c
	gcc -o exec  -g main.c q2_input.o baggage.o luggage_security.o weight.o boarding_pass.o immigration.o passport.o visa.o #security.o male_security.o
	
q2_input.o: q2_input.c
	gcc -g -c q2_input.c

baggage.o: baggage.c 
	gcc -g -c baggage.c
	
luggage_security.o: luggage_security.c
	gcc -g -c luggage_security.c

weight.o: weight.c
	gcc -g -c weight.c
	
boarding_pass.o: boarding_pass.c
	gcc -g -c boarding_pass.c
	
immigration.o: immigration.c
	gcc -g -c immigration.c
	
passport.o: passport.c
	gcc -g -c passport.c
	
visa.o: visa.c
	gcc -g -c visa.c

security.o: security.c
	gcc -g -c security.c

male_security.o: male_security.c
	gcc -g -c male_security.c



